import AboutusSection from '@/components/aboutus-section/aboutus-section';
import { Food } from '@/models/Food';
import { useAppDispatch } from '@/redux/hooks';

import dbConnect from '@/utils/db/dbConnect';
import Head from 'next/head';
import FoodSection from '../components/foods/food-section/food-section';
import HeroSection from '../components/hero-section/hero-section';
import { CATEGORIES } from '../DUMMY_DATA/foods';
import { ICategory } from '../utils/types/categories/category.interface';
import { IFood } from '../utils/types/foods/food.interface';

export interface HomePageProps {
  categories: ICategory[];
  foods: IFood[];
}

export default function HomePage({ foods, categories }: HomePageProps) {
  return (
    <>
      <div>
        <Head>
          <title>Pizza Shop</title>
          <meta name="description" content="Generated by Arvin Ramezani" />
          <link rel="icon" href="/images/pizza-logo.svg" />
        </Head>

        <HeroSection />

        <FoodSection foods={foods} categories={categories} />

        <AboutusSection />
      </div>
    </>
  );
}

export async function getStaticProps() {
  const categories: ICategory[] = CATEGORIES;

  await dbConnect();
  let foods = await Food.find({});
  foods = JSON.parse(JSON.stringify(foods));

  return {
    props: { foods, categories },
  };
}
